export interface PlayerAction {
  type: PlayerActionTypes;
  payload?: any;
}

export enum PlayerActionTypes {
  INITIALIZE_USER = 'INITIALIZE_USER',
  INITIALIZE_USER_INTERNAL = 'INITIALIZE_USER_INTERNAL',
  ADD_PLAYER = 'ADD_PLAYER',
  ADD_PLAYER_INTERNAL = 'ADD_PLAYER_INTERNAL',
  REMOVE_PLAYER = 'REMOVE_PLAYER',
  REMOVE_PLAYER_INTERNAL = 'REMOVE_PLAYER_INTERNAL',
  UPDATE_PLAYER = 'UPDATE_PLAYER',
  UPDATE_PLAYER_INTERNAL = 'UPDATE_PLAYER_INTERNAL',
  UPDATE_USER = 'UPDATE_USER',
  UPDATE_USER_INTERNAL = 'UPDATE_USER_INTERNAL',
  GET_USER = 'GET_USER',
  GET_USER_INTERNAL = 'GET_USER_INTERNAL',
  GET_PLAYER = 'GET_PLAYER',
  GET_PLAYER_INERNAL = 'GET_PLAYER_INTERNAL'
}

export interface Player {
  username: string;
  skill?: number;
  experience?: number;
  lfws?: string;
  name?: string;
};
export interface Players extends Array<Player>{};

export interface PlaygroundAction {
  type: PlaygroundActionTypes;
  payload?: any;
}

export interface Playground {
  id: string;
  name?: string;
  controller: string;
  players: Players;
  viewers: Players;
  active: true;
  createdAt: Date;
  updatedAt: Date;
}

export interface Playgrounds extends Array<Playground>{};

export enum PlaygroundActionTypes {
  INITIALIZE_PLAYGROUND = 'INITIALIZE_PLAYGROUND',
  INITIALIZE_PLAYGROUND_INTERNAL = 'INITIALIZE_PLAYGROUND_INTERNAL',
  REQUEST_PLAYGROUND = 'REQUEST_PLAYGROUND',
  REQUEST_PLAYGROUND_INTERNAL = 'REQUEST_PLAYGROUND_INTERNAL',
  START_PLAYGROUND = 'START_PLAYGROUND',
  START_PLAYGROUND_INTERNAL = 'START_PLAYGROUND_INTERNAL',
  STOP_PLAYGROUND = 'STOP_PLAYGROUND',
  STOP_PLAYGROUND_INTERNAL = 'STOP_PLAYGROUND_INTERNAL',
  ADD_PLAYGROUND = 'ADD_PLAYGROUND',
  ADD_PLAYGROUND_INTERNAL = 'ADD_PLAYGROUND_INTERNAL',
  REMOVE_PLAYGROUND = 'REMOVE_PLAYGROUND',
  REMOVE_PLAYGROUND_INTERNAL = 'REMOVE_PLAYGROUND_INTERNAL',
  UPDATE_PLAYGROUND = 'UPDATE_PLAYGROUND',
  UPDATE_PLAYGROUND_INTERNAL = 'UPDATE_PLAYGROUND_INTERNAL',
  GET_PLAYGROUND = 'GET_PLAYGROUND',
  GET_PLAYGROUND_INTERNAL = 'GET_PLAYGROUND_INTERNAL',
  SHARE_PLAYGROUND = 'SHARE_PLAYGROUND',
  SHARE_PLAYGROUND_INTERNAL = 'SHARE_PLAYGROUND_INTERNAL',
  CONNECT_PLAYGROUND = 'CONNECT_PLAYGROUND',
  CONNECT_PLAYGROUND_INTERNAL = 'CONNECT_PLAYGROUND'
}
